load("euler.mac")$

defstruct(graph(V, E))$

eulersberg: new(graph({A,B,C,D,E,F}, {[a,{E,F}], [b,{B,F}], [c,{B,F}], [d,{A,F}], [e,{A,F}], [f,{C,F}], [g,{A,C}], [h,{A,C}], [i,{C,D}], [k,{A,D}], [l,{D,E}], [m,{A,E}], [n,{A,E}], [o,{B,E}], [p,{A,B}]}))$

s: "EaFbBcFdAeFfCgAhCiDkAmEnApBoElD"$

journey: map(eval_string, charlist(s))$

print(concat(supcase("result: "), string(euler_path(eulersberg, journey))))$